<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_W_ls-inputfieldhelpbutton</name>
   <tag></tag>
   <elementGuidId>be5ccb63-977c-4a4e-99fb-de9d516c16aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ls-inputfieldhelpbutton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ls-inputfieldhelpbutton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ls-inputfieldhelpbutton</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fb64c334-bcdd-4ea1-9401-0ac2f8d7abf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ls-inputfieldhelpbutton</value>
      <webElementGuid>2c3c8034-941d-475c-a526-596f3bd71a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>IB</value>
      <webElementGuid>b0d6ba7a-e289-48a0-a5ed-2d3973b6c3e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>cf4eada7-60ee-4f1f-b276-43b13ed6f9f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>7265ea89-117e-4e9a-8736-00955024b8db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsField lsField--empty lsField--standalone pstxt lsField--explicitwidth lsField--monospace lsField--hasellipsis lsField--hover lsField--helpupperhover lsField--helpupperdown lsField--helpvisible lsField--showhelpalways lsField--appendhelp lsField--f4 lsField--focus lsField--interactiontarget lsField--beginofline</value>
      <webElementGuid>247e1b8a-f3ee-4ac4-8dbb-90934f882093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Plant</value>
      <webElementGuid>690812f6-2e79-4000-90d1-bc4dad00daca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ls-inputfieldhelpbutton&quot;)</value>
      <webElementGuid>db50bb00-d74f-440b-a466-f3faaab43674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/INT-PP-002/CREATION/CREATION WITH MANDATORY FIELD ONLY/Page_Create Work Center Initial Screen/iframe_Drag apps here to create links_appli_6322ab</value>
      <webElementGuid>12647f7c-b6eb-4b0c-b153-9a7e48cc5607</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ls-inputfieldhelpbutton']</value>
      <webElementGuid>b9264939-0b88-49e7-b722-b5de045085ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='M0:46']/div[8]/span</value>
      <webElementGuid>b885c0a9-e91a-4dbb-9715-8851cb63c42d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/span</value>
      <webElementGuid>ceb9dcfa-a81b-44c4-b65f-96807ba04448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ls-inputfieldhelpbutton' and @title = 'Plant']</value>
      <webElementGuid>6294b23b-48f0-45f1-9644-b6f5882b39ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
