<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Drag apps here to create links_appli_6322ab</name>
   <tag></tag>
   <elementGuidId>afc6c65a-36b9-40d3-bb40-63f5754bbedf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='application-WorkCenter-create-iframe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-WorkCenter-create-iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;application-WorkCenter-create-iframe&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>7a7e8db2-ca03-43d8-a18c-259aea8b7f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-WorkCenter-create-iframe</value>
      <webElementGuid>c19f8b03-ac31-4df4-b24c-6700f2edfce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>application-WorkCenter-create-iframe</value>
      <webElementGuid>b6fd677b-d100-41f6-8d45-90d01bdf80be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>application-WorkCenter-create-iframe</value>
      <webElementGuid>0d21da02-977d-429a-8718-645996ba908e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sap-orig-src</name>
      <type>Main</type>
      <value>/sap/bc/gui/sap/its/webgui;~sysid=QS4;~service=3200?~transaction=CR01&amp;sap-client=110&amp;sap-language=EN&amp;~nosplash=1&amp;sap-iframe-hint=GUI&amp;sap-ie=edge&amp;sap-theme=sap_horizon&amp;sap-target-navmode=inplace&amp;sap-keepclientsession=2&amp;sap-touch=0&amp;sap-ushell-timeout=0&amp;sap-shell=FLP1.108.0</value>
      <webElementGuid>02988c5d-f576-4d55-8104-d2737a3cbfd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Application</value>
      <webElementGuid>86f66403-cf31-4abc-86a9-b17f3a5d1446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sap-iframe-idx</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>21cc50e0-f764-4214-bf06-b05cb6b9ca25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>autoplay ;battery ;camera ;display-capture ;geolocation ;gyroscope ;magnetometer ;microphone ;midi ;clipboard-write ;clipboard-read ;fullscreen ;serial ;</value>
      <webElementGuid>b0218251-1421-4e5a-b14f-fb272482eb5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUShellApplicationContainer</value>
      <webElementGuid>99e66e4d-d241-4ee7-892b-e25ad3e1bdef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-WorkCenter-create-iframe&quot;)</value>
      <webElementGuid>6a22cb6f-86be-46c2-acc6-58d2420f9e52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='application-WorkCenter-create-iframe']</value>
      <webElementGuid>ecbfa3c7-b940-44d5-9bcd-d116ac138cd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-WorkCenter-create']/iframe</value>
      <webElementGuid>c97e4f25-d5fc-4cd7-bdd1-09b25502200f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>86efe81d-19bc-4567-861c-68bee147ce03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'application-WorkCenter-create-iframe' and @name = 'application-WorkCenter-create-iframe' and @title = 'Application']</value>
      <webElementGuid>ae541c18-e9b8-439f-b3d9-52b8a09bf845</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
