<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_S_ls-inputfieldhelpbutton</name>
   <tag></tag>
   <elementGuidId>0c8a581d-3953-42bc-ae65-9db0e6b23163</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ls-inputfieldhelpbutton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ls-inputfieldhelpbutton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ls-inputfieldhelpbutton</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>56ab6f94-22cd-499e-9b8e-42078231e58c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ls-inputfieldhelpbutton</value>
      <webElementGuid>c1439e7a-a4ac-4c56-b966-b46cb19da7e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>IB</value>
      <webElementGuid>b2bcf051-63b9-4d51-8eea-81098597fcbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e8f4f470-27a4-4945-994b-7a4cba69e5b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>447bbaf4-825a-46c7-beb2-4de0d75ca4a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsField lsField--empty lsField--standalone pstxt lsField--explicitwidth lsField--monospace lsField--hasellipsis lsField--hover lsField--helplowerhover lsField--helplowerdown lsField--helpvisible lsField--showhelpalways lsField--appendhelp lsField--f4 lsField--focus lsField--interactiontarget lsField--beginofline</value>
      <webElementGuid>3b03f9e7-01a6-437c-b68c-6978f6bdbc8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Person Responsible for the Work Center</value>
      <webElementGuid>82e65b72-639d-4668-ab97-ce33e5d6912a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ls-inputfieldhelpbutton&quot;)</value>
      <webElementGuid>01826bb4-88c9-45d3-9290-998009586640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/INT-PP-002/Creation/Creation with mandatory fields/Page_Create Work Center Basic Data/iframe_Drag apps here to create links_appli_6322ab</value>
      <webElementGuid>fd0cd0bf-09eb-4e3b-acd7-f87019667b49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ls-inputfieldhelpbutton']</value>
      <webElementGuid>1e8dd538-87e5-477c-8e88-b8b9f1e6a2c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='M0:46:2::0:0-scrl']/div[2]/span</value>
      <webElementGuid>6735fb4f-261e-4381-a59b-b8249c008b65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div[2]/span</value>
      <webElementGuid>2530d28a-fe24-4898-8a66-aa341b81698a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ls-inputfieldhelpbutton' and @title = 'Person Responsible for the Work Center']</value>
      <webElementGuid>f4b0d464-f4a9-4ac7-bc1a-3e5b7a767ae6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
