<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Next screenEmphasized</name>
   <tag></tag>
   <elementGuidId>58731fee-5567-4f35-a899-8b59a3361967</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='M0:50::btn[0]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Next screen Emphasized&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>388fe4ed-9a74-406e-a4df-2d9a7f752b99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>38af3397-b8f2-41f9-8957-cb33f2bf9c8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:50::btn[0]</value>
      <webElementGuid>7352ae79-5e99-4053-94f2-9bf7a3bb788d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>B</value>
      <webElementGuid>c050b8f3-7e63-4320-badd-3b9179594eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;0&quot;:&quot;Next screen&quot;,&quot;2&quot;:&quot;EMPHASIZED&quot;,&quot;4&quot;:&quot;Next screen (Enter)&quot;,&quot;18&quot;:&quot;N&quot;,&quot;19&quot;:&quot;ENTER&quot;,&quot;22&quot;:true,&quot;26&quot;:&quot;TOGGLE&quot;,&quot;28&quot;:{&quot;SID&quot;:&quot;wnd[0]/tbar[0]/btn[0]&quot;,&quot;Type&quot;:&quot;GuiButton&quot;,&quot;SubType&quot;:&quot;toolbar&quot;}}</value>
      <webElementGuid>32693237-114e-4952-8834-013f4a5b8e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsevents</name>
      <type>Main</type>
      <value>{&quot;Press&quot;:[{},{&quot;0&quot;:&quot;GuiOkCodeButton&quot;,&quot;1&quot;:&quot;vkey/0/ses[0]&quot;,&quot;2&quot;:true}]}</value>
      <webElementGuid>3f0c5749-26d6-435e-8eaf-d3a9c57dfc0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hint</name>
      <type>Main</type>
      <value>{&quot;WebAssistant&quot;:{&quot;id&quot;:{&quot;id&quot;:&quot;wnd[0]/tbar[0]/btn[0]&quot;,&quot;dynp&quot;:&quot;SAPLCRA0:101:CR01&quot;}}}</value>
      <webElementGuid>cd8e24ad-4d20-4adc-a039-deab7d48543d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4937fb43-18b1-42cc-93c8-090f6a604602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Next screen (Enter)</value>
      <webElementGuid>d4b36378-3678-4be1-b94b-08b8822b0dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ls-accesskey</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>390729e3-3fae-4790-8754-e389d6e3c743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accesskey</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>748a2fcf-625e-402a-b9c0-3a96cd15812d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d51d93d7-2fc1-4cd6-b147-e1f0c978bb9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a14d605e-2574-4ecf-b098-d455d7787c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsButton lsButton--base urInlineMetricTop urNoUserSelect urBtnRadius lsButton--useintoolbar lsButton--active lsButton--focusable lsButton--up lsButton--design-emphasized lsButton--hoverable</value>
      <webElementGuid>4bbeba58-7430-44f0-a378-163496716f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toolbaritem-id</name>
      <type>Main</type>
      <value>M0:50::btn[0]-r</value>
      <webElementGuid>6a80b442-5be4-472f-95b1-84f749bf9505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next screen Emphasized</value>
      <webElementGuid>b21a0d93-89a3-49a5-b530-dfb585e1dd42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:50::btn[0]&quot;)</value>
      <webElementGuid>509382c8-e32e-4569-831e-eb0163762452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/INT-PP-002/Creation/Duplicated work center name/Page_Create Work Center Initial Screen/iframe_Drag apps here to create links_appli_6322ab</value>
      <webElementGuid>7e8a8f53-3f07-4fb0-b012-e222d1ca5b4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='M0:50::btn[0]']</value>
      <webElementGuid>bf345ba4-2a03-4606-900c-115f74942713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='M0:50::btn[0]-r']/div</value>
      <webElementGuid>cc916643-9480-4f99-a4cb-bc449d2c1cd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Message Bar'])[1]/following::div[1]</value>
      <webElementGuid>48175971-6347-4cac-9224-f6ebc1af3a64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='W'])[3]/following::div[9]</value>
      <webElementGuid>d5e4de94-32c5-4310-90db-1483a65dab93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div</value>
      <webElementGuid>1a9c5daf-0001-473a-8e0e-3f7faddaf78a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'M0:50::btn[0]' and @title = 'Next screen (Enter)' and (text() = 'Next screen Emphasized' or . = 'Next screen Emphasized')]</value>
      <webElementGuid>bcc8fe91-4242-409a-9d52-aa986a4a69b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
