<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Drag apps here to create links_appli_6322ab</name>
   <tag></tag>
   <elementGuidId>2e422717-2b2c-4e08-93c2-ea2d2d7deef9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='application-WorkCenter-create-iframe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-WorkCenter-create-iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;application-WorkCenter-create-iframe&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>21c90516-c439-475d-affd-34d39f79b6fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-WorkCenter-create-iframe</value>
      <webElementGuid>58efeb56-ff30-46f9-bc8d-47c8c08f6bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>application-WorkCenter-create-iframe</value>
      <webElementGuid>268a336c-2e01-4c75-bd13-402c08b7bda9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>application-WorkCenter-create-iframe</value>
      <webElementGuid>d5f2510d-9f00-452e-8dad-bae4b1cae3ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sap-orig-src</name>
      <type>Main</type>
      <value>/sap/bc/gui/sap/its/webgui;~sysid=QS4;~service=3200?~transaction=CR01&amp;sap-client=110&amp;sap-language=EN&amp;~nosplash=1&amp;sap-iframe-hint=GUI&amp;sap-ie=edge&amp;sap-theme=sap_horizon&amp;sap-target-navmode=inplace&amp;sap-keepclientsession=2&amp;sap-touch=0&amp;sap-ushell-timeout=0&amp;sap-shell=FLP1.108.0</value>
      <webElementGuid>6dc7e08c-5fbe-4231-97e6-8e6840fef367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Application</value>
      <webElementGuid>de656ba0-59b2-4e52-934c-3bf7a58d896d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sap-iframe-idx</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f7f330d4-6a34-4dc7-bc9d-c07c425d621a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>autoplay ;battery ;camera ;display-capture ;geolocation ;gyroscope ;magnetometer ;microphone ;midi ;clipboard-write ;clipboard-read ;fullscreen ;serial ;</value>
      <webElementGuid>1c959805-9c16-4de5-8d40-669bd20c1312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUShellApplicationContainer</value>
      <webElementGuid>9ca64aa9-fc09-4be5-9425-b9b62a63eb84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-WorkCenter-create-iframe&quot;)</value>
      <webElementGuid>539cb26c-ac35-4a43-b681-333a59ff172f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='application-WorkCenter-create-iframe']</value>
      <webElementGuid>e19d4683-661c-46d7-a485-992a2f046971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-WorkCenter-create']/iframe</value>
      <webElementGuid>1660ce39-bc3f-4ad1-bebd-18098eb583dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>d1eb2599-65ba-40ec-b281-0ff9f185e56b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'application-WorkCenter-create-iframe' and @name = 'application-WorkCenter-create-iframe' and @title = 'Application']</value>
      <webElementGuid>ad6a01c4-e618-464c-a77e-b4e0751e3bad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
