<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_W_ls-inputfieldhelpbutton</name>
   <tag></tag>
   <elementGuidId>08a59592-338e-41da-b6b6-5a5c0a22fdcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ls-inputfieldhelpbutton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ls-inputfieldhelpbutton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ls-inputfieldhelpbutton</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>28d0badc-f40c-4cc2-a0bf-bcb2a259eb11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ls-inputfieldhelpbutton</value>
      <webElementGuid>9b2643f1-eae7-44aa-bf4b-a7673a182772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>IB</value>
      <webElementGuid>09164a27-872a-4319-a534-a5714cb66593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>41dbf30e-bcd4-4417-8d93-e1401927c005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>5aeef192-9bcd-4bc5-b7e9-91136b2c35f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsField lsField--empty lsField--standalone pstxt lsField--explicitwidth lsField--monospace lsField--hasellipsis lsField--hover lsField--helplowerhover lsField--helplowerdown lsField--helpvisible lsField--showhelpalways lsField--appendhelp lsField--f4 lsField--focus lsField--interactiontarget lsField--beginofline</value>
      <webElementGuid>18ae5b04-2127-4130-8035-680f817c93ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Plant</value>
      <webElementGuid>2d42c618-15f9-4b6f-bc4a-58663ca00aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ls-inputfieldhelpbutton&quot;)</value>
      <webElementGuid>41db8688-1413-401a-9956-3f26d445b252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/INT-PP-002/Creation/Duplicated work center name/Page_Create Work Center Initial Screen/iframe_Drag apps here to create links_appli_6322ab</value>
      <webElementGuid>90925e36-8009-45dd-ad38-857fb0ab5d36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ls-inputfieldhelpbutton']</value>
      <webElementGuid>145cae87-01b6-4182-a3bc-37ba7af37055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='M0:46']/div[8]/span</value>
      <webElementGuid>6ec342ba-a195-471e-94cc-df72c28fa85d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/span</value>
      <webElementGuid>6e44298b-ebe3-4c30-82fa-2745866af1fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ls-inputfieldhelpbutton' and @title = 'Plant']</value>
      <webElementGuid>8fb9f6cb-f773-4b6c-bec8-e6404abc3993</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
