<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>922470df-b885-406f-a0c1-a0436764ab6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='sh[3,0]#sc']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.urBorderBox.lsSapTable--expandWidth.lsSTCellHeight100.urSTSCOuterDiv.urSTRowSelSecIcon.urST4LbSelIcon > div.urST5SCMetricInner.lsSapTable--expandHeight</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#SHresultgrid1-mrss-cont-left-Row-2 div >> internal:has-text=&quot;Row selected. To deselect the row, press CTRL and the spacebar.&quot;i >> div</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c222a3b2-2411-4401-9e45-b60468177f45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3583e9a0-e046-4c3e-93ae-877733e2e555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>bb06e6ff-8c21-4b15-acfc-a3a4713c596d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>urST5SCMetricInner lsSapTable--expandHeight</value>
      <webElementGuid>0ed252a1-76ba-4c48-97f6-e3dfa89847de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>7ae55014-e95b-413f-8123-a84351662cc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sh[3,0]#sc&quot;)/div[@class=&quot;urBorderBox lsSapTable--expandWidth lsSTCellHeight100 urSTSCOuterDiv urSTRowSelSecIcon urST4LbSelIcon&quot;]/div[@class=&quot;urST5SCMetricInner lsSapTable--expandHeight&quot;]</value>
      <webElementGuid>d24991c4-016d-4233-bb67-221c60c5992c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/INT-PP-002/CREATION/CREATION WITH MANDATORY FIELD/Page_Create Work Center Basic Data/iframe_Drag apps here to create links_appli_6322ab</value>
      <webElementGuid>c128cbc9-07cb-4eb0-88b6-2c4b6fa9a8c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='sh[3,0]#sc']/div/div</value>
      <webElementGuid>b2d7d045-a813-4cd2-b225-a9d0cc64d839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To select a row, press the spacebar.'])[2]/following::div[2]</value>
      <webElementGuid>60c3af24-3e43-43f9-86f5-1a8f7d3f25c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To select a row, press the spacebar.'])[1]/following::div[4]</value>
      <webElementGuid>d2ce01f4-9821-4e2f-a157-5653cac7ced1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Row selected. To deselect the row, press CTRL and the spacebar.'])[1]/preceding::div[1]</value>
      <webElementGuid>e8b5cf35-9fb3-425f-b3f5-b962b6c905d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To select a row, press the spacebar.'])[3]/preceding::div[2]</value>
      <webElementGuid>f332f871-3bab-4aee-899f-c85599fd8124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr[2]/td/div/div/table/tbody/tr[3]/td/div/div</value>
      <webElementGuid>e7598113-e313-4ef2-989a-368dcc13c4f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' ' or . = ' ')]</value>
      <webElementGuid>6ebed228-9ecd-4a0c-ad4a-7e5e43f85edb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
