<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_S_InputField</name>
   <tag></tag>
   <elementGuidId>2d553f18-6351-4c9b-b143-8687becd09ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='M0:46:2:3B256::10:22']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Standard Value Key&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a97acbf3-bca4-409b-ae57-3797d2b6a227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:46:2:3B256::10:22</value>
      <webElementGuid>9b69b512-73a7-43a6-a049-6b2dff7dcc53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>CBS</value>
      <webElementGuid>41e265bf-e95c-49f5-9f8d-87bcd18e283d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;x&quot;:0,&quot;1&quot;:&quot;FREETEXT&quot;,&quot;3&quot;:&quot;M0:46:2:3B256::10:22_TALB&quot;,&quot;7&quot;:true,&quot;12&quot;:true,&quot;13&quot;:&quot;S&quot;,&quot;14&quot;:&quot;SERVER&quot;,&quot;16&quot;:true,&quot;20&quot;:false,&quot;21&quot;:{&quot;SID&quot;:&quot;wnd[0]/usr/tabsTAXI_TABSTRIP_OVERVIEW/tabpGRND/ssubSUBSCREEN_BODY:SAPLCRA0:3000/ctxtP3000-VGWTS&quot;,&quot;Type&quot;:&quot;GuiCTextField&quot;,&quot;maxlen&quot;:4,&quot;focusable&quot;:&quot;X&quot;},&quot;22&quot;:&quot;pstxt&quot;,&quot;29&quot;:&quot;M0:46:2:3B256::10:1&quot;}</value>
      <webElementGuid>30db1236-f221-4d21-a1ec-799d3b2c8847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsevents</name>
      <type>Main</type>
      <value>{&quot;Change&quot;:[{},{&quot;1&quot;:&quot;value&quot;,&quot;3&quot;:true,&quot;7&quot;:true}],&quot;Select&quot;:[{},{&quot;1&quot;:&quot;value&quot;,&quot;3&quot;:true,&quot;7&quot;:true}],&quot;Validate&quot;:[{},{}],&quot;DeleteItem&quot;:[{},{&quot;3&quot;:true}],&quot;ListAccess&quot;:[{&quot;ResponseData&quot;:&quot;delta&quot;,&quot;TransportMethod&quot;:&quot;full&quot;,&quot;EnqueueCardinality&quot;:&quot;none&quot;},{&quot;3&quot;:true,&quot;8&quot;:&quot;history&quot;,&quot;limitlen&quot;:&quot;X&quot;}],&quot;FieldHelpPress&quot;:[{},{&quot;1&quot;:&quot;vkey/4&quot;,&quot;2&quot;:true,&quot;5&quot;:true}],&quot;ClipboardTablePaste&quot;:[{},{&quot;0&quot;:&quot;GuiTextField&quot;,&quot;1&quot;:&quot;action/25&quot;,&quot;2&quot;:true,&quot;3&quot;:true}]}</value>
      <webElementGuid>556a9521-1c39-49ee-89cb-718f3160b44c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hint</name>
      <type>Main</type>
      <value>{&quot;WebAssistant&quot;:{&quot;id&quot;:{&quot;id&quot;:&quot;wnd[0]/usr/tabsTAXI_TABSTRIP_OVERVIEW/tabpGRND/ssubSUBSCREEN_BODY:SAPLCRA0:3000/ctxtP3000-VGWTS&quot;,&quot;dynp&quot;:&quot;SAPLCRA0:4000:CR01&quot;,&quot;name&quot;:&quot;P3000-VGWTS&quot;}}}</value>
      <webElementGuid>9837f175-9e8a-4403-b208-b23858552775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c5feea3b-f2eb-4e2f-be19-8110f802c7e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ls-accesskey</name>
      <type>Main</type>
      <value>S</value>
      <webElementGuid>1fb950c0-620b-4949-86d9-b6dbab016161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accesskey</name>
      <type>Main</type>
      <value>S</value>
      <webElementGuid>0182f6c7-9d01-4756-86cc-5627be9c0e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>33da9591-17df-448b-a882-a57680b93fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>4766e452-0597-4a16-abee-88bca0dc3822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>33b29134-69ae-4bad-9d3d-4ed89d7226b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ed61861b-6fcd-4e30-8532-649aedfbe5f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Standard Value Key</value>
      <webElementGuid>ea4b73c6-d6cb-4e56-8242-b3170eb5a626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsField__input</value>
      <webElementGuid>e4499c35-fe6e-4feb-88aa-34b69f3620b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>f25f8547-93b5-4ae3-b0f3-7bca0873b771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cd348d35-fb5f-4aeb-86e6-211f2a32f874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value> ARIA_CB_F4Lookup_TUT</value>
      <webElementGuid>d73fdf6d-7593-48a1-b391-200935d9b07a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>M0:46:2:3B256::10:1</value>
      <webElementGuid>c9daef74-fa63-4821-b17c-c6d614328ecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>InputField</value>
      <webElementGuid>3df7c316-bf79-43d0-934d-3dced874545a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:2:3B256::10:22&quot;)</value>
      <webElementGuid>d60595ea-03e0-4bf7-a44c-ca30f21cdca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/INT-PP-002/CREATION/CREATION WITH MANDATORY FIELD/Page_Create Work Center Basic Data/iframe_Drag apps here to create links_appli_6322ab</value>
      <webElementGuid>d87f22b1-b0a3-42a5-b0a4-fcc87a424ba2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='M0:46:2:3B256::10:22']</value>
      <webElementGuid>d5b85e7e-a786-4d24-bf94-8a67501b708a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='M0:46:2:3B256::10:22-r']/tbody/tr/td/input</value>
      <webElementGuid>b6e1dae0-878a-4b4f-a2a2-0d6e5fce3398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr[2]/td/table/tbody/tr/td/div/div/div/div[2]/table/tbody/tr/td/input</value>
      <webElementGuid>e41b4676-b189-4c08-b54f-ec73ee4879b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'M0:46:2:3B256::10:22' and @type = 'text' and @title = 'Standard Value Key' and @name = 'InputField']</value>
      <webElementGuid>5cb25b92-1ef5-404f-aec7-e8e26f4af5d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
