<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_OKEmphasized</name>
   <tag></tag>
   <elementGuidId>7419d05f-8456-474f-86d7-6a1751227f78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='NSH1_copy']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NSH1_copy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;OK Emphasized&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6e8a25d0-f279-4832-ab91-0f7de242c88f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>34a001a6-54b5-4968-ac59-8eb2254325f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NSH1_copy</value>
      <webElementGuid>3a6f7b70-bde4-42da-b236-a6456925a25d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>B</value>
      <webElementGuid>f52195aa-e19f-457b-8cb3-cade59f87715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;0&quot;:&quot;OK&quot;,&quot;2&quot;:&quot;EMPHASIZED&quot;,&quot;4&quot;:&quot;Copy&quot;,&quot;18&quot;:&quot;O&quot;,&quot;22&quot;:true,&quot;26&quot;:&quot;TOGGLE&quot;,&quot;28&quot;:{&quot;SID&quot;:&quot;wnd[1]/shell/gridRESULT/tbar/btnCOPY&quot;,&quot;Type&quot;:&quot;GuiSearchHelp&quot;,&quot;SubType&quot;:&quot;toolbar&quot;}}</value>
      <webElementGuid>ede04e50-1e34-42cc-9e01-2886a0833542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsevents</name>
      <type>Main</type>
      <value>{&quot;Press&quot;:[{},{&quot;1&quot;:&quot;action/3&quot;,&quot;2&quot;:true,&quot;3&quot;:true}]}</value>
      <webElementGuid>e02f204d-bfe0-4f96-83c5-645fea9658a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fccb721f-e392-423d-a945-54487e999967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Copy</value>
      <webElementGuid>862d83b9-b471-4976-b28e-e4e9727dcb46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ls-accesskey</name>
      <type>Main</type>
      <value>O</value>
      <webElementGuid>72ae4f1c-bda6-4e0c-9909-a9d8d62b101a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accesskey</name>
      <type>Main</type>
      <value>O</value>
      <webElementGuid>a8b9b36f-64cf-457d-a5a9-739a7c422e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b7c033be-f87b-4474-9e83-be5b00c397af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9d5cc5b2-832f-47af-ab19-637241f734f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsButton lsButton--base urInlineMetricTop urNoUserSelect urBtnRadius lsButton--useintoolbar lsButton--active lsButton--focusable lsButton--up lsButton--design-emphasized lsButton--hoverable</value>
      <webElementGuid>b2d223fb-ce4b-46d1-b8e7-21ba68dad604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toolbaritem-id</name>
      <type>Main</type>
      <value>NSH1_copy-r</value>
      <webElementGuid>c2232e82-0337-4f65-9ea0-cb96a8a957a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK Emphasized</value>
      <webElementGuid>63f3ddc7-5972-405b-b948-f143d098c26a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NSH1_copy&quot;)</value>
      <webElementGuid>d4ada175-82ff-4408-b0b1-0a90375f652c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/INT-PP-002/Creation/Creation with mandatory fields/Page_Create Work Center Initial Screen/iframe_Drag apps here to create links_appli_6322ab</value>
      <webElementGuid>989e1824-f36e-4296-a451-4640a66452d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='NSH1_copy']</value>
      <webElementGuid>a7354760-5f7e-407f-9ce9-d4e779b814f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='NSH1_copy-r']/div</value>
      <webElementGuid>eb675d98-b062-4203-b776-190883824ad8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COFICAB - MED Virtual Plant'])[2]/following::div[21]</value>
      <webElementGuid>f6a1d63c-493f-4e66-8c4a-a69afe320c24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COFICAB - MED'])[4]/following::div[24]</value>
      <webElementGuid>dd33d84c-3ed9-429d-89af-2215f53a4161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/div/div/span[2]/div</value>
      <webElementGuid>bc62a7d0-cdf5-4fce-8129-a8757acf23ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'NSH1_copy' and @title = 'Copy' and (text() = 'OK Emphasized' or . = 'OK Emphasized')]</value>
      <webElementGuid>fe8f5f39-72f3-4765-8aba-3ac5a6b6431b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
