<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Drag apps here to create links_appli_6322ab</name>
   <tag></tag>
   <elementGuidId>cdfe6e18-7707-48c0-b653-607f8f82d062</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='application-WorkCenter-create-iframe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-WorkCenter-create-iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;application-WorkCenter-create-iframe&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>00aef67f-1812-4134-8e95-744a95f48129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-WorkCenter-create-iframe</value>
      <webElementGuid>c2f6884a-3afe-40c9-aadd-37f1a4783b8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>application-WorkCenter-create-iframe</value>
      <webElementGuid>cc13884c-5b58-49d8-a145-1b36234ae47c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>application-WorkCenter-create-iframe</value>
      <webElementGuid>16ee2197-a658-4e91-94e6-8d7dacb1751f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sap-orig-src</name>
      <type>Main</type>
      <value>/sap/bc/gui/sap/its/webgui;~sysid=QS4;~service=3200?~transaction=CR01&amp;sap-client=110&amp;sap-language=EN&amp;~nosplash=1&amp;sap-iframe-hint=GUI&amp;sap-ie=edge&amp;sap-theme=sap_horizon&amp;sap-target-navmode=inplace&amp;sap-keepclientsession=2&amp;sap-touch=0&amp;sap-ushell-timeout=0&amp;sap-shell=FLP1.108.0</value>
      <webElementGuid>21386ed6-c287-41d0-a3b2-e343858e7019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Application</value>
      <webElementGuid>af95f768-3e27-488d-a7a3-58b16f50d2e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sap-iframe-idx</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>32cb2ac4-b243-4f47-a0f6-5f245ddc97b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>autoplay ;battery ;camera ;display-capture ;geolocation ;gyroscope ;magnetometer ;microphone ;midi ;clipboard-write ;clipboard-read ;fullscreen ;serial ;</value>
      <webElementGuid>a2d85dc9-3b73-49b9-98a3-bcb087da61af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUShellApplicationContainer</value>
      <webElementGuid>00eedac9-c2aa-48d5-a585-d58abfba6fcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-WorkCenter-create-iframe&quot;)</value>
      <webElementGuid>9d9d1676-e287-490a-b092-8ae16562d49d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='application-WorkCenter-create-iframe']</value>
      <webElementGuid>c9e0bc97-f1e3-4f02-b48e-5eedaeb749f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-WorkCenter-create']/iframe</value>
      <webElementGuid>47dc250c-7e93-4f72-a123-ee43b4238c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>aa1a68ee-3851-4977-8528-6e1771867c7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'application-WorkCenter-create-iframe' and @name = 'application-WorkCenter-create-iframe' and @title = 'Application']</value>
      <webElementGuid>d08f7419-9cfc-4340-8869-a86d3097224e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
