<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_W_ls-inputfieldhelpbutton</name>
   <tag></tag>
   <elementGuidId>d1bbd88e-314c-401f-bef2-bb4b22c3d1c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ls-inputfieldhelpbutton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ls-inputfieldhelpbutton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ls-inputfieldhelpbutton</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3af7dd62-e9a8-4d60-a7d6-50c4474eae11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ls-inputfieldhelpbutton</value>
      <webElementGuid>dbbb6763-6439-4aea-902d-991c574d9908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>IB</value>
      <webElementGuid>2cd2e09c-b6f3-4152-92ec-05fc7bc63873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>93cd9175-888c-4c47-a485-ad785088443b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d5635cfc-c19d-4df7-95b9-0e042c939349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsField lsField--empty lsField--standalone pstxt lsField--explicitwidth lsField--monospace lsField--hasellipsis lsField--hover lsField--helpupperhover lsField--helpupperdown lsField--helpvisible lsField--showhelpalways lsField--appendhelp lsField--f4 lsField--focus lsField--interactiontarget lsField--beginofline</value>
      <webElementGuid>1579ff8d-96d6-4e09-971a-93f27a1121e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Plant</value>
      <webElementGuid>c283a2aa-0a22-49b0-9c47-dc19ee6017af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ls-inputfieldhelpbutton&quot;)</value>
      <webElementGuid>e8469953-b306-4358-8e76-58ca34782915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/INT-PP-002/Creation/Creation with mandatory fields/Page_Create Work Center Initial Screen/iframe_Drag apps here to create links_appli_6322ab</value>
      <webElementGuid>20f4dd68-7e78-4c17-a518-d14ea1004329</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ls-inputfieldhelpbutton']</value>
      <webElementGuid>fb10caaa-122b-4b65-82a6-5acc724d5073</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='M0:46']/div[8]/span</value>
      <webElementGuid>add1dcc5-23ad-433a-85f0-568bf39f9992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/span</value>
      <webElementGuid>0235f5ca-1de1-4468-bd1b-5beaa4092a03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ls-inputfieldhelpbutton' and @title = 'Plant']</value>
      <webElementGuid>da1cfee8-0ae8-43b4-a735-b03fcb437aae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
