<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_OKEmphasized</name>
   <tag></tag>
   <elementGuidId>af0714fd-e61d-4be5-8518-5b005e52548a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='NSH1_copy']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NSH1_copy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;OK Emphasized&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>62d21ecc-268e-4cc7-a5fd-2aee7f0dcc1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e2d3c0b4-7354-4bbc-a7a8-da05484413d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NSH1_copy</value>
      <webElementGuid>a52c5140-2061-4e69-8f37-3663edfa7ad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>B</value>
      <webElementGuid>69046e75-405a-4859-9a89-992efe221b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;0&quot;:&quot;OK&quot;,&quot;2&quot;:&quot;EMPHASIZED&quot;,&quot;4&quot;:&quot;Copy&quot;,&quot;18&quot;:&quot;O&quot;,&quot;22&quot;:true,&quot;26&quot;:&quot;TOGGLE&quot;,&quot;28&quot;:{&quot;SID&quot;:&quot;wnd[1]/shell/gridRESULT/tbar/btnCOPY&quot;,&quot;Type&quot;:&quot;GuiSearchHelp&quot;,&quot;SubType&quot;:&quot;toolbar&quot;}}</value>
      <webElementGuid>426cd9c4-55d8-41f5-ab26-7fe4239a6661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsevents</name>
      <type>Main</type>
      <value>{&quot;Press&quot;:[{},{&quot;1&quot;:&quot;action/3&quot;,&quot;2&quot;:true,&quot;3&quot;:true}]}</value>
      <webElementGuid>07950b11-aae3-45e0-baa5-c17ce8bdda9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f14ce922-d114-452f-8bf6-a68221f3dfe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Copy</value>
      <webElementGuid>58d794e5-f139-4900-aa62-a3dbb3b9ea2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ls-accesskey</name>
      <type>Main</type>
      <value>O</value>
      <webElementGuid>420f3ad7-fc38-437f-9982-c4f6b81c5ed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accesskey</name>
      <type>Main</type>
      <value>O</value>
      <webElementGuid>32b54be1-2f0f-4933-8247-21215055ffce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>10fcda99-278d-4ed0-8c9a-883282765c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>344a68a2-81b4-46a8-a128-32de4cb3551f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsButton lsButton--base urInlineMetricTop urNoUserSelect urBtnRadius lsButton--useintoolbar lsButton--active lsButton--focusable lsButton--up lsButton--design-emphasized lsButton--hoverable</value>
      <webElementGuid>ef6aad49-2a4f-44b5-b275-d676af23b832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toolbaritem-id</name>
      <type>Main</type>
      <value>NSH1_copy-r</value>
      <webElementGuid>10068715-d648-47ed-be51-6494e03cd84f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK Emphasized</value>
      <webElementGuid>ff0e0fca-d0b5-40f8-a236-8eb5de602d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NSH1_copy&quot;)</value>
      <webElementGuid>80cd2259-6639-47b6-abde-8bedb036a7a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/INT-PP-002/CREATION/CREATION WITH MANDATORY FIELD/Page_Create Work Center Initial Screen/iframe_Drag apps here to create links_appli_6322ab</value>
      <webElementGuid>fd0137ab-886e-4344-a0ba-138983386c4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='NSH1_copy']</value>
      <webElementGuid>4466ccaa-9a0f-4597-a468-f0a23c048fe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='NSH1_copy-r']/div</value>
      <webElementGuid>03b1d03a-f5a2-4d72-a935-c05bf6e9761c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COFICAB - MED Virtual Plant'])[2]/following::div[21]</value>
      <webElementGuid>e2f44b8c-790c-40da-a95d-58482a08b062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COFICAB - MED'])[4]/following::div[24]</value>
      <webElementGuid>9d878a4c-7af9-43a0-8143-155bbe5f8142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/div/div/span[2]/div</value>
      <webElementGuid>6201c1b3-ed2e-4d8e-aeb2-b2e2b70a1ae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'NSH1_copy' and @title = 'Copy' and (text() = 'OK Emphasized' or . = 'OK Emphasized')]</value>
      <webElementGuid>1cfffd3e-d1fd-481b-9e96-8f408a64a083</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
