<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_S_ls-inputfieldhelpbutton</name>
   <tag></tag>
   <elementGuidId>10c8c86d-a6d5-4316-aa19-4cd653200b50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ls-inputfieldhelpbutton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ls-inputfieldhelpbutton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ls-inputfieldhelpbutton</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9b8b64dc-287b-4684-a0e4-f76ba99cde3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ls-inputfieldhelpbutton</value>
      <webElementGuid>5d5a5d41-9395-4985-80c9-5e28da87e591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>IB</value>
      <webElementGuid>3e5ca94d-8480-4ce1-9825-78d241838ebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>9c0593ba-8485-4d6a-8f97-fdbd386709c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f3d5af14-2054-465a-bf41-c04b848f9753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsField lsField--empty lsField--standalone pstxt lsField--explicitwidth lsField--monospace lsField--hasellipsis lsField--hover lsField--helpupperhover lsField--helpupperdown lsField--helpvisible lsField--showhelpalways lsField--appendhelp lsField--f4 lsField--focus lsField--interactiontarget lsField--beginofline</value>
      <webElementGuid>d5321d88-c23f-4c0c-9090-6745ca5dd947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Person Responsible for the Work Center</value>
      <webElementGuid>fdfe41a0-086b-43cd-9ca5-1cd34ebe40ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ls-inputfieldhelpbutton&quot;)</value>
      <webElementGuid>52886737-e8fe-4494-84c6-bea3f067b00b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/INT-PP-002/CREATION/CREATION WITH MANDATORY FIELD ONLY/Page_Create Work Center Basic Data/iframe_Drag apps here to create links_appli_6322ab</value>
      <webElementGuid>fba34d70-6e04-459d-a821-2b8574ecdc1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ls-inputfieldhelpbutton']</value>
      <webElementGuid>17ff951c-3509-4f38-9afa-064964906f3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='M0:46:2::0:0-scrl']/div[2]/span</value>
      <webElementGuid>7f039712-73b9-4426-a815-d78e4f597621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div[2]/span</value>
      <webElementGuid>dca282cd-0915-48ed-b78b-66472c97c508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ls-inputfieldhelpbutton' and @title = 'Person Responsible for the Work Center']</value>
      <webElementGuid>c30529c8-ee5b-42cd-987d-d6f6906af3b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
