<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_All_searchFieldInShell-button-img</name>
   <tag></tag>
   <elementGuidId>0109aefb-6adb-437c-9856-a60f0bc066fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='searchFieldInShell-button-img']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchFieldInShell-button-img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Focus Search&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3210e201-ed0f-471c-bad9-57bf0ce8129c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchFieldInShell-button-img</value>
      <webElementGuid>8f1b40d2-8c42-47db-bb81-695e4fc16e3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>searchFieldInShell-button-img</value>
      <webElementGuid>12daadaa-4ec1-49f5-9054-21ff4bb9d186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>73109a81-69aa-45da-ada1-1f31f77f71cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c36a0227-4765-4240-8fa2-8ae60bb67597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-icon-content</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>5ef85aaa-682b-43dd-836c-e7ff578439bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUiIcon sapMBtnCustomIcon sapMBtnIcon sapMBtnIconLeft</value>
      <webElementGuid>f00cc4f8-f0c4-4b4a-9fb7-1bca02e8482f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchFieldInShell-button-img&quot;)</value>
      <webElementGuid>99e7811e-92d4-414b-8815-fa8a2efcdd26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='searchFieldInShell-button-img']</value>
      <webElementGuid>d5fa6b49-3d27-4e4d-881d-7c33b3f76249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='searchFieldInShell-button-inner']/span</value>
      <webElementGuid>038cb2a0-2a0e-4cb6-89db-d28e251f35f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span/span</value>
      <webElementGuid>227920a1-eb24-4f9b-9344-0db6404ce972</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'searchFieldInShell-button-img']</value>
      <webElementGuid>274bdaa8-0624-4f26-8da7-38679704f034</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
